config/routes.rb
OnlineEdu::Application.routes.draw do
  #resources :groups

  resources :online_quiz_grades

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config
  get "home/index"
  #get "courses/new"

  #get "courses/index"

  #get "courses/create"

  #get "courses/update"

  resources :online_answers

  resources :online_quizzes

  resources :documents

  resources :quiz_grades

  resources :answers

  resources :questions
  
  resources :evaluations do
    collection do
      get 'get'
    end
  end

 # namespace :teacher do
 #   resources :courses
 # end  

  resources :courses do
  member do
    get 'remove_student'
    get 'add_student'
    get 'student_show'
    get 'courseware'
    get 'courseware_teacher'
    get 'enrolled_students'
    get 'progress_teacher'
    get 'progress_teacher_detailed'
    get 'progress'
    post 'student_quiz'
    get 'student_notifications'
    get 'course_editor'
    get 'student_grade'
    get 'dynamic_quizzes'
    get 'student_quiz_grade'
    get 'student_lecture_grade'
    get 'send_email'
    post 'send_email_through'
    get 'send_batch_email'
    post 'send_batch_email_through'
    
  end
    match '/events(/:year(/:month))' => 'events#index', :as => :event, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
    match "events/:id" => "events#show"
    resources :announcements do
      member do
        get 'reload'
      end
    end
    resources :groups do #at first had it over quizzes and lectures, but then a lecture/quiz might not be part of a module! so shouldn't need module to access lecture.. could create lectures and then put them part of a group.
      member do
        get 'new_or_edit'
        get 'group_editor'
        get 'statistics'
        get 'details'
        get 'display_quizzes'
        get 'display_questions'
        get 'new_document'
        get 'review_questions'
        post 'save_review_questions'
      end
      collection do
        post 'sort'
      end
    end
    resources :quizzes do
      member do
        get 'new_or_edit'
        get 'middle'
        get 'details'
        put 'update_questions'
      end
      collection do
        post 'sort'
      end
    end
    resources :lectures do
      member do
        get 'add_quiz'
        get 'remove_quiz'
        get 'coordinates'
        get 'add_answer'
        get 'remove_answer'
        get 'get_answers'
        #get 'save_answers'
        get 'save_answers2'
        get 'save_online'
        get 'answered'
        get 'insert_quiz'
        get 'confused'
        get 'confused_question'
        get 'seen'
        get 'new_or_edit'
        get 'new_quiz'
        get 'save_duration'
        get 'back'
        get 'pause'
        get 'getOldData'
        get 'middle'
        get 'details'
        get 'reload_invideo_quizzes'
      end
      collection do
        post 'sort'
      end
    end    
  end

  authenticated :user do
    #root :to => 'home#index'
    root :to => 'courses#index' #later make this home#index when we have a home#index!!
  end
  
  #authenticated :admin_user do
  #  root :to => 'admin#dashboard'
  #end
  
  root :to => "home#index"
  
  devise_for :users
  resources :users do
    member do
      get "enroll"
      post "enroll_to_course"
    end
  end
  
end

app/models/lecture.rb
class Lecture < ActiveRecord::Base
  
  validates :name, :url,:appearance_time, :due_date,:course_id, :group_id, :due_date, :presence => true
  validates_inclusion_of :appearance_time_module, :due_date_module, :in => [true, false] #not in presence because boolean false considered not present.
  has_many :online_quizzes, :dependent => :destroy, :order => "time"
  has_many :backs, :dependent => :destroy
  has_many :confuseds, :dependent => :destroy
  has_many :pauses, :dependent => :destroy
  has_many :evaluations, :dependent => :destroy
  has_many :lecture_questions, :dependent => :destroy
  has_many :lecture_views, :dependent => :destroy
  has_many :online_quiz_grades, :dependent => :destroy
  belongs_to :course, :touch => true
  belongs_to :group
  has_many :events
  after_destroy :clean_up
  
  attr_accessible :course_id, :description, :name, :url, :group_id, :appearance_time, :due_date, :duration, :slides, :appearance_time_module, :due_date_module, :position
  acts_as_list :scope => :group
  
  accepts_nested_attributes_for :online_quizzes, :allow_destroy => true

  def has_not_appeared
    return appearance_time > Time.zone.now.to_date
  end
  
  def done?(user_asking) #marks lecture as done IF all quizzes solved AND passed all 25/50/75 marks.
    lecture_quizzes=online_quizzes.pluck(:id).sort #ids of lecture quizzes
    user_quizzes=OnlineQuizGrade.where(:user_id => user_asking, :lecture_id => id).pluck(:online_quiz_id).sort  
    #will add now the marks.
    viewed=LectureView.where(:user_id => user_asking, :lecture_id => id) #, :percent => 75
    print viewed
    #print "answer iSSSSSSSSSS"
    #print user_quizzes==lecture_quizzes and !viewed.empty?
    #user_quizzes==lecture_quizzes
    # changed it because sometimes user has solved more! when a quiz is deleted..
    return ( user_quizzes&lecture_quizzes == lecture_quizzes and !viewed.empty?)
    
    
    
  end
  
  def edit_url
    return "Edit URL"
  end
  
    def get_data
    data={}
     online_quizzes.each do |quiz|
        data[quiz.id]=[]
        quiz.online_answers.each do |answer|
          data[quiz.id]<< OnlineQuizGrade.where(:online_quiz_id => quiz.id, :online_answer_id => answer.id, :lecture_id => id).count
        end
      end
    return data
  end
  
  def get_colors
    colors={}
      online_quizzes.each do |quiz|
        colors[quiz.id]=[]
        quiz.online_answers.each do |answer|
          color = if answer.correct
                    "green"
                  else
                    "gray"
                  end
          colors[quiz.id]<< color
        end
      end
    return colors
  end
  
  def get_categories
    data={}
      online_quizzes.each do |quiz|
        data[quiz.id] = quiz.online_answers.map{|obj| obj=obj.answer}
      end
    return data
  end
  
  
  def get_questions
    data={}
      online_quizzes.each do |quiz|
        data[quiz.id] = [quiz.question, quiz.time]
      end
    return data
  end
  
  def get_question_ids
    data=[]
      online_quizzes.each do |quiz|
        data << quiz.id
      end
    return data
  end
  
  def convert_short_to_long_url
     vid=/(?:https?:\/{2})?(?:w{3}\.)?youtu(?:be)?\.(?:com|be)(?:\/watch\?v=|\/)([^\s&]+)/.match(url)
     if !vid.nil?
       vid= vid[1]
       self.url= "http://www.youtube.com/watch?v=#{vid}"
       print url
       save 
     end
  end
  
  private
  def clean_up
    self.events.where(:quiz_id => nil).destroy_all
  end
  

end

app/models/lecture_view.rb
class LectureView < ActiveRecord::Base
  attr_accessible :course_id, :lecture_id, :user_id, :percent, :updated_at
  belongs_to :lecture
  
  validates :course_id, :lecture_id, :user_id, :presence => true  #:percent
end

app/controllers/lectures_controller.rb
class LecturesController < ApplicationController
  # GET /lectures
  # GET /lectures.json
  before_filter :set_zone
  
  def set_zone
    @course=Course.find(params[:course_id])
    Time.zone= @course.time_zone
  end
    
  def index
    @lectures = Lecture.where(:course_id => params[:course_id])
    @course= Course.find(params[:course_id])
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @lectures }
    end
  end

  # GET /lectures/1
  # GET /lectures/1.json
  def show
    #@lecture = Lecture.find(params[:id])
    #@course = Course.find(params[:course_id])
    
    @lecture=Lecture.where(:id => params[:id], :course_id => params[:course_id])
    @course = Course.find(params[:course_id])
    
    if @lecture.empty?
      redirect_to course_lectures_path(params[:course_id]), :alert=> "No such lecture"
    else
    
    @lecture=@lecture.first
    
   
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @lecture }
    end
    end
  end

  # GET /lectures/new
  # GET /lectures/new.json
  def new
    @lecture = Lecture.new
    @course = Course.find(params[:course_id])

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @lecture }
    end
  end

  # GET /lectures/1/edit
  def edit
    #@lecture = Lecture.find(params[:id])
    #@course = Course.find(params[:course_id])
    
    @lecture=Lecture.where(:id => params[:id], :course_id => params[:course_id])
    @course = Course.find(params[:course_id])
    
    if @lecture.empty?
      redirect_to course_lectures_path(params[:course_id]), :alert=> "No such lecture"
    else
      @lecture=@lecture.first
    end
  end

  # POST /lectures
  # POST /lectures.json
  def create
    @lecture = Lecture.new(params[:lecture])
    @lecture.course_id = params[:course_id]
    @course= Course.find(params[:course_id])
    
    respond_to do |format|
      if @lecture.save
        format.html { redirect_to [@course,@lecture], notice: 'Lecture was successfully created.' }
        format.json { render json: @lecture, status: :created, location: @lecture }
      else
        format.html { render action: "new" }
        format.json { render json: @lecture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /lectures/1
  # PUT /lectures/1.json
  def update
    @lecture = Lecture.find(params[:id])
    @course= Course.find(params[:course_id])
    
    @lecture.events.where(:quiz_id => nil, :group_id => @lecture.group.id).destroy_all
    
    #if same as module, then i will change the due date/ appearance date to be like the module.
    if params[:lecture][:due_date_module]=="1" #and params[:lecture][:due_date_module]=="true"
      params[:lecture][:due_date]=@lecture.group.due_date
    end 
    
    if params[:lecture][:appearance_time_module]=="1" #and params[:lecture][:appearance_time_module]=="true"
      params[:lecture][:appearance_time]=@lecture.group.appearance_time
    end 
    
    #can't change due_date/ appearance_time if boolean is true (take from module)
 #   if params[:lecture][:due_date] and @lecture.due_date_module==true
 #     params[:lecture][:due_date]=@lecture.group.due_date
 #   end
    
 #   if params[:lecture][:appearance_time] and @lecture.appearance_time_module==true
 #     params[:lecture][:appearance_time]=@lecture.group.appearance_time
 #   end
    
    respond_to do |format|
      if @lecture.update_attributes(params[:lecture])
        
        #@lecture.due_date = @lecture.due_date.next_day #end_of_day
        #@lecture.save
        print "lecture due date is #{@lecture.due_date.to_formatted_s(:db) }"
        print "lecture appearance date is #{@lecture.appearance_time.to_formatted_s(:db) }"
        print "group due_date is #{@lecture.group.due_date.to_formatted_s(:db) }"
        print "group appearance date is #{@lecture.group.appearance_time.to_formatted_s(:db) }"
        print @lecture.due_date != @lecture.group.due_date
        print @lecture.appearance_time != @lecture.group.appearance_time
        
        @type= "lecture_#{@lecture.id}"
        
        #comparing without the fractional part of the second.
        if @lecture.due_date.to_formatted_s(:number) != @lecture.group.due_date.to_formatted_s(:number) or @lecture.appearance_time.to_formatted_s(:number) != @lecture.group.appearance_time.to_formatted_s(:number)
          print @lecture.due_date.to_formatted_s(:number)
          print @lecture.group.due_date.to_formatted_s(:number)
          @lecture.events << Event.new(:name => "#{@lecture.name} due", :start_at => params[:lecture][:due_date], :end_at => params[:lecture][:due_date], :all_day => false, :color => "red", :course_id => @course.id, :group_id => @lecture.group.id)
        end
        format.html { redirect_to [@course, @lecture], notice: 'Lecture was successfully updated.' }
        format.json { head :no_content }
        format.js{}
      else
        format.html { render action: "edit" }
        format.json { render json: @lecture.errors, status: :unprocessable_entity }
      end
    end
  end

  def add_quiz #creating an online quiz and add in to this lecture at specified time.
    logger.debug("in add quiz!!!!!!")
    OnlineQuiz.create(:lecture_id => params[:id], :time => params[:time])
    @quizzes= OnlineQuiz.where(:lecture_id => params[:id])#.pluck(:time)
    @course= Course.find(params[:course_id])
    @lecture= Lecture.find(params[:id])
    @loc= course_lecture_path(@course,@lecture)
    @loc2=remove_quiz_course_lecture_path(@course,@lecture)
    @loc3=coordinates_course_lecture_path(@course,@lecture)
    render json: {:q => @quizzes, :loc => @loc, :loc2=> @loc2, :loc3 => @loc3} 
  end
  
  def remove_quiz  #destroy an online quiz
    logger.debug("in remove quiz!!!!!!")
    @a=OnlineQuiz.find(params[:quiz])
    @a.destroy
    @course= Course.find(params[:course_id])
    @lecture= Lecture.find(params[:id])
    @quizzes= OnlineQuiz.where(:lecture_id => params[:id])#.pluck(:time)
    @loc= course_lecture_path(@course,@lecture)
    @loc2=remove_quiz_course_lecture_path(@course,@lecture)
    @loc3=coordinates_course_lecture_path(@course,@lecture)
    render json: {:q => @quizzes, :loc => @loc, :loc2=> @loc2, :loc3 => @loc3} 
    
   # render json: {:q => @quizzes} 
  end
  
  def insert_quiz
    @lecture=Lecture.where(:id => params[:id], :course_id => params[:course_id])
    @course = Course.find(params[:course_id])
    
    if @lecture.empty?
      redirect_to course_lectures_path(params[:course_id]), :alert=> "No such lecture"
    else
    
    @lecture=@lecture.first
    
    
    @quizzes= OnlineQuiz.where(:lecture_id => params[:id])
    @url= get_answers_course_lecture_path(params[:course_id], params[:id])
    @s=params[:s] if params[:s]
    logger.debug("s issssss #{@s}")
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @lecture }
    end
    end
  end
  # DELETE /lectures/1
  # DELETE /lectures/1.json
  def coordinates # getting the answers of a specific online quiz
    #@quiz=OnlineQuiz.find(params[:quiz])
    @quiz=OnlineQuiz.where(:id => params[:quiz], :lecture_id => params[:id])
    @course= Course.find(params[:course_id])
    @lecture= Lecture.find(params[:id])
    
    if @quiz.empty?
      redirect_to course_lecture_path(@course, @lecture), :alert => "Requested quiz does not exist"
    else
      @quiz=@quiz.first
      @old= OnlineAnswer.where(:online_quiz_id => params[:quiz]).to_json
    end
    
  end
  
  def getOldData
    @old= OnlineAnswer.where(:online_quiz_id => params[:quiz])#.to_json
    render json: {:old => @old}
  end
  
  def add_answer #creating an online answer, and associating it with an online quiz.
    logger.debug("in add answer!!!#{params[:flag]}")
    if params[:flag]!="false"
      @current=OnlineAnswer.create(:online_quiz_id => params[:quiz], :xcoor => params[:left], :ycoor => params[:top], :correct => false)
    end
    @answers= OnlineAnswer.where(:online_quiz_id => params[:quiz])#.pluck(:time)
    @course= Course.find(params[:course_id])
    @lecture= Lecture.find(params[:id])
    @loc= coordinates_course_lecture_path(@course,@lecture, :quiz => params[:quiz])
    @loc2=remove_answer_course_lecture_path(@course,@lecture)
    #@save= save_answers_course_lecture_path(@course,@lecture)
    #@loc3=coordinates_course_lecture_path(@course,@lecture)
    render json: {:a => @answers, :loc => @loc, :loc2=> @loc2, :save => @save, :current => @current}#, :loc3 => @loc3}
  end
  
  def save_answers2
    
    @data=params[:stored]
    @course= Course.find(params[:course_id])
    @lecture= Lecture.find(params[:id])
    @data||=[]
    @data.each do |k,v|
      OnlineAnswer.find(k.to_i).update_attributes(:explanation => v[2],:answer => v[1], :correct => v[0] , :ycoor => v[3], :xcoor => v[4])
    end
    
    #redirect_to course_lecture_path(@course,@lecture)
    render json: {:done => "done"}
  end
  
  # def save_answers
    # @course= Course.find(params[:course_id])
    # @lecture= Lecture.find(params[:id])
    # #Just need to save now.
    # @reasons=params[:reason] || []
    # @xcoor=params[:xcoor] || []
    # @ycoor=params[:ycoor] || []
#     
    # @reasons.each do |k,v|
      # OnlineAnswer.find(k.to_i).update_attributes(:answer => v)
    # end
#     
    # @xcoor.each do |k,v|
      # OnlineAnswer.find(k.to_i).update_attributes(:xcoor => v)
    # end
#     
    # @ycoor.each do |k,v|
      # OnlineAnswer.find(k.to_i).update_attributes(:ycoor => v)
    # end
# 
#     
    # #update correct and all others not correct.
#     
    # if params[:quiz]
      # OnlineQuiz.find(params[:quiz].keys[0].to_i).online_answers.each do |a|
        # a.update_attributes(:correct => false)
      # end
      # OnlineAnswer.find(params[:quiz].values[0].to_i).update_attributes(:correct => true)
    # end
#     
    # redirect_to course_lecture_path(@course,@lecture)
  # end
  

app/helpers/lectures_helper.rb
module LecturesHelper
  def online_quiz_done(id, user_id)
    return !OnlineQuizGrade.where(:user_id => user_id, :online_quiz_id => id).empty?
  end
end

app/views/lectures/coordinates.html.erb
<script src="http://popcornjs.org/code/dist/popcorn-complete.js"></script>
<style>
	.ontop{
		/*background:#fff;  /* invisible div*/
        position:absolute;
        min-width:800px;
        min-height:500px;
        z-index:2;
	}
	
	.myclass{
		width:250px;
	}
</style>

<%= render 'shared/head' %>

<div class="row">
<div class="span3">
<div style="width:100%;height:150px;">
<center style="margin-top: 30px">Drag the button: <%= image_tag "button6.png", :class=> "component"%>
<br><!-- <input class="btn" value="Save and Exit" onclick="saveAll()"/> -->
<%= button_to "Save and Exit", course_lecture_path(@course,@lecture), :class => "btn", :onclick => "saveAll()", :method => :get , :remote=> true%>	
</center>
</div>
</div>
		
<div class="span9">
	
<center><div class="ontop2" style="width:800px;border:8px solid;margin-top:30px;" >
<div class="ontop" id="ontop"></div>
<div id="youtube" style="width:800px;height:500px;"></div>
<div id="foo"></div>
</div></center>
</div>



<script language="JavaScript" type="text/JavaScript">

var storedData={}

function onDoubleClick(elem)
{
	console.debug("in this one"+elem);
	elem.popover('show');
}
function callFirst()
{
	alert("here");
}
function remove(elem)
{
	// This method called controller action to remove answer from DB
	// It also removes it from the screen and the storedData hash
	$.getJSON('<%= remove_answer_course_lecture_path(@course,@lecture) %>',{"answer":elem , "quiz":<%= @quiz.id %>}, function(resp){
	});
	$("#"+elem).remove()
	delete storedData[elem];	
}
function save(elem)
{
	// Save the explanation and the correct to storedData
	storedData[elem]=[document.getElementById("correct_"+elem).checked, document.getElementById("explain_"+elem).value]
	console.debug("element is "+elem);
	console.debug("explanation is "+document.getElementById("explain_"+elem).value)
	console.debug("correct is "+document.getElementById("correct_"+elem).checked)
	if(storedData[elem][0]==true)
	{
		for(key in storedData)
		{
			if(key==elem)
				continue;
			storedData[key][0]=false
		}
	}
}
function saveAll()
{
	// This is called at the very end, to save everything in the storedData and positions to the database.
	// Then redirect to lecture page.
	console.debug(storedData)
	for(key in storedData){
		console.debug("key:"+storedData[key])
		storedData[key].push.apply(storedData[key],[$('#'+key).position().top,$('#'+key).position().left]);
	}
	console.debug(storedData)
	
	$.getJSON('<%= save_answers2_course_lecture_path(@course, @lecture) %>',{"stored":storedData}, function(resp){
		console.debug(resp)
		console.debug("calling redirect")
		redirect()
	});
}
function redirect()
{
	console.debug("in redirect")
	window.location = "<%= insert_quiz_course_lecture_path(@course, @lecture)  %>"
}
function load(elem)
{
	// When call popover, its loaded from here.
	console.debug("elem is "+elem)
	document.getElementById("correct_"+elem).checked=storedData[elem][0]
	document.getElementById("explain_"+elem).value=storedData[elem][1]
}

jQuery(function() {
	var count=0;
	// This is to make the image draggable, and clone it when dragged.
    jQuery(".component").draggable({
        //  use a helper-clone that is append to 'body' so is not 'contained' by a pane
        helper: function() {
        	//callFirst(); // can call function here to save button for example..
            z=jQuery(this).clone().appendTo('.ontop').css({
                'zIndex': 5, 'position':'absolute'
            }).attr("id","circle_"+count)//.attr("ondbclick","callme()");
            count++;
            
            console.debug("z is "+z)
            return z;
        },
        cursor: 'move',
        containment: ".ontop"
       
    });
	var toadd=""
	// makes ontop droppable
    jQuery('.ontop').droppable({
        //activeClass: 'ui-state-hover',
        accept: '.component',
        drop: function(event, ui) {
            if (!ui.draggable.hasClass("dropped")){
            	
            	
            	toadd=jQuery(ui.helper).clone().addClass("dropped").draggable({cursor: 'move', containment: ".ontop"});
        		 jQuery(this).append(toadd);
                
                // first drop, then create it in the database, and set all parameters.
                $.getJSON('<%= add_answer_course_lecture_path(@course, @lecture) %>',{"left":toadd.position().left, "top":toadd.position().top, "quiz": <%=@quiz.id %>, "flag":true}, function(resp){
                	
                	storedData[resp['current'].id]=[false,""]
                	console.debug("current id issss "+ resp['current'].id)
                	console.debug("to add isss "+toadd.attr("id"))
                	toadd.attr("id", ""+resp['current'].id) 
                	console.debug("to add isss "+toadd.attr("id"))
                	toadd.attr("onclick","load('"+toadd.attr('id')+"')")
	        		toadd.attr("rel","popover").attr("data-content","Correct:<input name='group1' id='correct_"+toadd.attr('id') +"' style='margin-left:20px;margin-bottom:2px' type='radio'/><br>Explanation:<input id='explain_"+toadd.attr('id') +"' type='text' /><br><input type='button'  class='btn btn-primary' value='Save' onclick=save('"+toadd.attr('id')+"') data-dismiss='clickover' /><input type='button' data-dismiss='clickover' class='btn' value='Cancel'/><input type='button' onclick=remove('"+toadd.attr('id')+"') class='btn btn-danger' value='Remove' data-dismiss='clickover'/>")//.attr()
	                toadd.attr("data-original-title","")
	                toadd.clickover({ global_close: false, template:  '<div class="popover myclass"><div class="arrow"></div><div class="popover-inner myclass"><div class="popover-content"><p></p></div></div></div>'})//.dblclick(function() {
               
                });
                }else{
                	// dragging inside the div
                
                toadd=jQuery(ui.helper)  // every time a button is dragged it is here in toadd. could get its position and save it.
                
                console.debug("new position is "+toadd.position().top+" and id is "+toadd.id+" explanation is ")//+document.getElementById('explain_'+toadd.id).value() )
                }
               
            }
        });
    });


$(document).ready(function() {
  //first of all, will get the data at the very beginning
  var old= <%= raw @old %>
  for(i=0; i<old.length; i++)
  {               
  	var toadd = $('<img />').attr({ 'id': old[i].id , 'src': '/assets/button6.png' });
  	toadd= toadd.addClass("component").addClass("dropped").draggable({cursor: 'move',containment: ".ontop"});
    storedData[old[i].id]=[old[i].correct,old[i].answer]
    toadd.css({"top":old[i].ycoor+"px", "left":old[i].xcoor+"px", 'zIndex': 5, 'position':'absolute'})
    toadd.attr("onclick","load('"+toadd.attr('id')+"')")
	toadd.attr("rel","popover").attr("data-content","Correct:<input group='group1' id='correct_"+toadd.attr('id') +"' style='margin-left:20px;margin-bottom:2px' type='radio'/><br>Explanation:<input id='explain_"+toadd.attr('id') +"' type='text' /><br><input type='button'  class='btn btn-primary' value='Save' onclick=save('"+toadd.attr('id')+"') data-dismiss='clickover' /><input type='button' data-dismiss='clickover' class='btn' value='Cancel'/><input type='button' onclick=remove('"+toadd.attr('id')+"') class='btn btn-danger' value='Remove' data-dismiss='clickover'/>")//.attr()
	toadd.attr("data-original-title","")
	toadd.clickover({ global_close: false, template:  '<div class="popover myclass"><div class="arrow"></div><div class="popover-inner myclass"><div class="popover-content"><p></p></div></div></div>'})//.dblclick(function() {
     $('#ontop').append(toadd)           
  }
});


</script>
 



<!-- Should move this somewhere else later -->

<script>

var pop


document.addEventListener( "DOMContentLoaded", function() {
	
pop = Popcorn.youtube( "#youtube", "<%=  @lecture.url %>",{ width: 400, controls: 0}); //youtube unlike normal html5 needs to be run from a webserver
//var pop = Popcorn( Popcorn.youtube( '#youtube', 'http://www.youtube.com/watch?v=H9BXF6xJy54', { width: 400, controls: 0 } ) );

pop.controls( false ); 
 
pop.on("loadeddata", function(){
	this.currentTime(<%= @quiz.time %>)
	this.pause;
	 console.debug("pop duration isss"+this.currentTime())  
	});                        

                          

}, false );



$(document).ready(function() {
  $('.ontop').click(function(e) {
    var offset = $(this).offset();
  	left= parseFloat(e.pageX) - parseFloat(offset.left) //not clientX because client depends on window.. so numbers change when scrolling.
  	right = parseFloat(e.pageY) - parseFloat(offset.top)
  	
  	console.debug("offset is "+ left)
  	console.debug("left is "+left + " and top is "+right)
  	
    //document.getElementById('pos').innerHTML = 'Mouse position is: X='+left+' Y='+right;
	//document.getElementById('pos').style.left = left;
	//document.getElementById('pos').style.top = right;
	//document.getElementById('pos').style.display='block';
  });
});


</script>
</div>

app/views/lectures/details.js.erb
//console.log("back")
$('#details').html("<%= escape_javascript(raw render("details", :lecture => @lecture))%>");

app/views/lectures/index.html.erb
<%= render 'shared/head' %>
<h1>Listing lectures</h1>

<table class="table table-striped">
  <tr>
    
    <th>Name</th>
    <th>Description</th>
    <th>Url</th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @lectures.each do |lecture| %>
  <tr>
    
    <td><%= lecture.name %></td>
    <td><%= lecture.description %></td>
    <td><%= lecture.url %></td>
    <td><%= link_to 'Show', [@course, lecture] %></td>
    <td><%= link_to 'Edit', edit_course_lecture_path(@course,lecture) %></td>
    <td><%= link_to 'Insert Quizzes', insert_quiz_course_lecture_path(@course,lecture) %></td>
    <td><%= link_to 'Destroy', [@course, lecture], method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Lecture', new_course_lecture_path(@course) %>