config/routes.rb
OnlineEdu::Application.routes.draw do
  #resources :groups

  resources :online_quiz_grades

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config
  get "home/index"
  #get "courses/new"

  #get "courses/index"

  #get "courses/create"

  #get "courses/update"

  resources :online_answers

  resources :online_quizzes

  resources :documents

  resources :quiz_grades

  resources :answers

  resources :questions
  
  resources :evaluations do
    collection do
      get 'get'
    end
  end

 # namespace :teacher do
 #   resources :courses
 # end  

  resources :courses do
  member do
    get 'remove_student'
    get 'add_student'
    get 'student_show'
    get 'courseware'
    get 'courseware_teacher'
    get 'enrolled_students'
    get 'progress_teacher'
    get 'progress_teacher_detailed'
    get 'progress'
    post 'student_quiz'
    get 'student_notifications'
    get 'course_editor'
    get 'student_grade'
    get 'dynamic_quizzes'
    get 'student_quiz_grade'
    get 'student_lecture_grade'
    get 'send_email'
    post 'send_email_through'
    get 'send_batch_email'
    post 'send_batch_email_through'
    
  end
    match '/events(/:year(/:month))' => 'events#index', :as => :event, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
    match "events/:id" => "events#show"
    resources :announcements do
      member do
        get 'reload'
      end
    end
    resources :groups do #at first had it over quizzes and lectures, but then a lecture/quiz might not be part of a module! so shouldn't need module to access lecture.. could create lectures and then put them part of a group.
      member do
        get 'new_or_edit'
        get 'group_editor'
        get 'statistics'
        get 'details'
        get 'display_quizzes'
        get 'display_questions'
        get 'new_document'
        get 'review_questions'
        post 'save_review_questions'
      end
      collection do
        post 'sort'
      end
    end
    resources :quizzes do
      member do
        get 'new_or_edit'
        get 'middle'
        get 'details'
        put 'update_questions'
      end
      collection do
        post 'sort'
      end
    end
    resources :lectures do
      member do
        get 'add_quiz'
        get 'remove_quiz'
        get 'coordinates'
        get 'add_answer'
        get 'remove_answer'
        get 'get_answers'
        #get 'save_answers'
        get 'save_answers2'
        get 'save_online'
        get 'answered'
        get 'insert_quiz'
        get 'confused'
        get 'confused_question'
        get 'seen'
        get 'new_or_edit'
        get 'new_quiz'
        get 'save_duration'
        get 'back'
        get 'pause'
        get 'getOldData'
        get 'middle'
        get 'details'
        get 'reload_invideo_quizzes'
      end
      collection do
        post 'sort'
      end
    end    
  end

  authenticated :user do
    #root :to => 'home#index'
    root :to => 'courses#index' #later make this home#index when we have a home#index!!
  end
  
  #authenticated :admin_user do
  #  root :to => 'admin#dashboard'
  #end
  
  root :to => "home#index"
  
  devise_for :users
  resources :users do
    member do
      get "enroll"
      post "enroll_to_course"
    end
  end
  
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  load_and_authorize_resource 
  # GET /online_answers
  # GET /online_answers.json
  
  before_filter :getCourse
  before_filter :correct_user
  before_filter :set_zone
 
  
  def set_zone
    @course=Course.find(params[:course_id])
    Time.zone= @course.time_zone
  end
  
  def getCourse
    @course= Course.find(params[:course_id])  
  end
  
  def correct_user
    # Checking to see if the current user is taking the course OR teaching the course, otherwise he is not authorised.
    @c=Course.find(params[:course_id])
    if !@c.users.include?(current_user) and !(@c.user == current_user)
      redirect_to courses_path, :alert => "You are not authorized to see requested page"
    end
  end
  def index
    @groups = @course.groups

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @groups }
    end
  end

  # GET /online_answers/1
  # GET /online_answers/1.json
  def show
      @group = @course.groups.find(params[:id])
      logger.debug("group isss #{@group.name}")
      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @group }
      end
  rescue #ActiveRecord::RecordInvalid because recordnot found
        flash[:error] = "Group not found"
        redirect_to :action => :index 
  end

  # GET /online_answers/new
  # GET /online_answers/new.json
  def new
    @group=@course.groups.build()
    #@group = Group.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @group }
    end
  end

  # GET /online_answers/1/edit
  def edit
    begin
      @group = @course.groups.find(params[:id])
    rescue
      flash[:error] = "Group not found"
      redirect_to :action => :index
    end
  end

  # POST /online_answers
  # POST /online_answers.json
  def create
    #@group = Group.new()
    @group = @course.groups.build(params[:group])

    respond_to do |format|
      if @group.save
        format.html { redirect_to [@course,@group], notice: 'Group was successfully created.' }
        format.json { render json: @group, status: :created, location: @group }
      else
        format.html { render action: "new" }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /online_answers/1
  # PUT /online_answers/1.json
  def update
     if params[:id].nil?
        redirect_to :action => :create
     end
    @group = @course.groups.find(params[:id])
    
    # When I update the module, I need to update the event as well. Can destroy it and create it again since I have only one event per module.
    # If the lecture/quiz have different appearance or due dates, then I create a separate event for them as well. (but only one per lecture/quiz as well (for due date only))
    @group.events.where(:quiz_id => nil, :lecture_id => nil).destroy_all #its ok since I only have the due date.
    
    
    respond_to do |format|
      if @group.update_attributes(params[:group])
        #@group.due_date= @group.due_date.next_day #end_of_day #because if 15 sep.. then due date should be beg of 16.
        #@group.save
        print params[:group][:due_date]
        print "due is"
        print @group.due_date
        
        @group.events << Event.new(:name => "#{@group.name} due", :start_at => params[:group][:due_date], :end_at => params[:group][:due_date], :all_day => false, :color => "red", :course_id => @course.id)
        
        # also change due date and appearance date of all lectures/quizzes with boolean checked.
        @group.lectures.each do |l|
          if l.appearance_time_module
            l.appearance_time = @group.appearance_time
          end
          if l.due_date_module
            l.due_date = @group.due_date
          end
          l.save
        end
        
        @group.quizzes.each do |q|
          if q.appearance_time_module
            q.appearance_time = @group.appearance_time
          end
          if q.due_date_module
            q.due_date = @group.due_date
          end
          q.save
        end
        
        @course= @group.course
        @group_new=@group
        
        #@type="group_#{@group.id}"
        if !@group.get_items.empty?
          @type= "#{@group.get_items[0].class.name.downcase}_#{@group.get_items[0].id}"
        end
        
        format.html { redirect_to [@course,@group], notice: 'Group was successfully updated.' }
        format.json { head :no_content }
        format.js{}
      else
        format.html { render action: "edit" }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /online_answers/1
  # DELETE /online_answers/1.json
  def destroy
    @group = @course.groups.find(params[:id])
    group_lectures=@group.lectures.pluck(:id)
    group_quizzes=@group.quizzes.pluck(:id)
    @group.destroy

    
    respond_to do |format|
      format.html { redirect_to course_editor_course_url(@course) }
      format.json { head :no_content }
      format.js { render "delete", :locals => {:rem => params[:id], :group_lectures =>group_lectures, :group_quizzes => group_quizzes }}
    end
  end
  
  def new_or_edit #called from course_editor / module editor to add a new module
    print "here"
    #render json: "a" => "b" 
    @group = @course.groups.build(:name => "New Module", :appearance_time => Time.zone.now.to_date, :due_date => 1.week.from_now.to_date) #added to_date so it won't have time.
    @group.events << Event.new(:name => "#{@group.name} due", :start_at => 1.week.from_now.to_date, :end_at => 1.week.from_now.to_date, :all_day => false, :color => "red", :course_id => @course.id)
    
      if @group.save
        @updated = @group.appearance_time.strftime('%d %b (%a)')
        @updatedDue = @group.due_date.strftime('%d %b (%a)')
        logger.debug("appearance time isssss #{@updated}")
        respond_to do |format|
          format.html {}
          format.json {}
          format.js { render "reload_editor", :locals => {:rem => @course}}
        end
         
      
      else
       logger.debug(@group.errors.full_messages)
        render json: @group.errors, status: :unprocessable_entity 
      end
    
  end
  
  
   def sort #called from course_editor to sort the modules (by dragging)
   @groups = Group.where(:course_id => @course.id)
   @groups.each do |f|
     f.position = params['group'].index(f.id.to_s) + 1
     f.save
   end
   render json: {"done"=>"done"}
   end
   
 
   def group_editor
     #stopped here
     # Getting the lecture/quiz/onlinequiz to render on the right hand side using a javascript partial.
     @group=Group.find(params[:id])
     @lecture= Lecture.find(params[:lec]) if params[:lec]
     @quiz=OnlineQuiz.where(:id => params[:quiz], :lecture_id => params[:lec]) if params[:quiz]
     @real_quiz=Quiz.where(:id => params[:real_quiz], :group_id => params[:id], :course_id => params[:course_id]) if params[:real_quiz]
     #if @quiz
     #  render :partial => "groups/coordinates"
     #end
     
     #getting order
     @all = @group.lectures + @group.quizzes
     @all.sort!{|x,y| ( x.position and y.position ) ? x.position <=> y.position : ( x.position ? -1 : 1 )  }
     @to_return=[]
     @all.each do |s|
       @to_return<< "#{s.class.name.downcase}_#{s.id}"
     end
     
     logger.debug("in here in coord yayyyy quiz issss #{params[:quiz]}")
     
    if params[:quiz]
    if @quiz.empty?
      redirect_to group_editor_course_group_path(@course, @group), :alert => "Requested quiz does not exist"
    else
      @quiz=@quiz.first
      @old= OnlineAnswer.where(:online_quiz_id => params[:quiz]).to_json
    end
    end
     
    if params[:real_quiz]
    if @real_quiz.empty?
      redirect_to group_editor_course_group_path(@course, @group), :alert => "Requested quiz does not exist"
    else
      @real_quiz=@real_quiz.first
    end
    end
    
     respond_to do |format|
      format.html {}
      format.js { 
        if params[:quiz]
          render "videocoordinates", :locals => {:lec => @lecture}
        elsif params[:lec]
          render "videoquiz", :locals => {:lec => @lecture}
        elsif params[:real_quiz]
          render "quiz", :locals => {:q => @real_quiz}
        end
         
        
        }
      
      end
   end
   
   def statistics
     @group_new= Group.find(params[:id])
     #render json: {"group"=>@group_new}
     respond_to do |format|
      format.js{}
      end
   end
   
   def details
     @group_new = Group.find(params[:id])
     respond_to do |format|
      format.js{}
      end
   end
   
   def save_review_questions
    to_hide= params[:hide]  
    if !to_hide.nil?
        @hide= to_hide.keys  
    else
        @hide=[]
    end
    
    @hide= @hide.map{|e| e.to_i}
    @group=Group.find(params[:id])
    @lectures= @group.lectures.pluck(:id)
    
    puts "hide is #{@hide.inspect}"
    LectureQuestion.where(:lecture_id => @lectures).each do |l|
      if @hide.include?(l.id)
        #l.update_attributes(:hide => true)
        l.hide = true
        l.save if l.hide_changed?
      else
        l.hide = false
        l.save if l.hide_changed?
      end
    end
     
    
     redirect_to review_questions_course_group_path(@course, @group)
    
    
   end
   def review_questions
     
    @course=Course.find(params[:course_id])
    @students=@course.users
    @quizzes=@course.quizzes.where("quiz_type IS NULL or quiz_type != 'survey'")
    @student_names=[]
    @type = "modules"
    @highlight= "group_#{@group.id}"
    @group=Group.find(params[:id])
     
     @lectures= @group.lectures.pluck(:id)
     @lecture_questions2 = [] #LectureQuestion.where(:lecture_id => @lectures)
     @lectures.each do |l|
       @lecture_questions2<<LectureQuestion.where(:lecture_id => l).order(:time)
     end
     @lecture_questions2.flatten!
     
     render "courses/progress_teacher"
   end
   
   def display_quizzes    

app/helpers/groups_helper.rb
module GroupsHelper
  
  
end

app/views/groups/_coordinates.html.erb
<head>
<script src="http://popcornjs.org/code/dist/popcorn-complete.js"></script>
<style>
	.ontop{
		/*background:#fff;  /* invisible div*/
        position:absolute;
        min-width:500px;
        min-height:281px;
        z-index:2;
	}
	
	.myclass{
		width:250px;
	}
</style>

<script language="JavaScript" type="text/JavaScript">

var storedData={}

function onDoubleClick(elem)
{
	//console.debug("in this one"+elem);
	elem.popover('show');
}
function callFirst()
{
	alert("here");
}
function remove(elem)
{
	// This method called controller action to remove answer from DB
	// It also removes it from the screen and the storedData hash
	$.getJSON('<%= remove_answer_course_lecture_path(@course,@lecture) %>',{"answer":elem , "quiz":<%= @quiz.id %>}, function(resp){
	});
	$("#"+elem).remove()
	delete storedData[elem];	
}
function save(elem)
{
	// Save the explanation and the correct to storedData
	storedData[elem]=[document.getElementById("correct_"+elem).checked, document.getElementById("answer_"+elem).value, document.getElementById("explain_"+elem).value]
	//console.debug("element is "+elem);
	//console.debug("explanation is "+document.getElementById("explain_"+elem).value)
	//console.debug("correct is "+document.getElementById("correct_"+elem).checked)
	if(storedData[elem][0]==true)
	{
		for(key in storedData)
		{
			if(key==elem)
				continue;
			storedData[key][0]=false
		}
	}
	
	// when update text save all
	saveAll();
}
function saveAll()
{
	// This is called at the very end, to save everything in the storedData and positions to the database.
	// Then redirect to lecture page.
	console.debug(storedData)
	var storedData2={}
	for(key in storedData){
		storedData2[key]=[]
		console.debug("key:"+storedData[key])
		//storedData2[key].push.apply(storedData2[key],storedData[key],[$('#'+key).position().top,$('#'+key).position().left]);
		storedData2[key]= storedData[key].concat([$('#'+key).position().top,$('#'+key).position().left])
	}
	console.debug(storedData)
	console.debug(storedData2)
	
	$.getJSON('<%= save_answers2_course_lecture_path(@course, @lecture) %>',{"stored":storedData2}, function(resp){
		console.debug(resp)
		console.debug("calling redirect")
	//	$('#notify').html("<div class='alert alert-success'>Saved</div>")
		//redirect()
		
	});
}
function redirect()
{
	console.debug("in redirect")
	window.location = "<%= group_editor_course_group_path(@course,@group,:lec => @lecture.id)  %>"
}
function load(elem)
{
	// When call popover, its loaded from here.
	console.debug("elem is "+elem)
	document.getElementById("correct_"+elem).checked=storedData[elem][0]
	document.getElementById("explain_"+elem).value=storedData[elem][2]
	document.getElementById("answer_"+elem).value=storedData[elem][1]
}

jQuery(function() {
	var count=0;
	// This is to make the image draggable, and clone it when dragged.
    jQuery(".component").draggable({
        //  use a helper-clone that is append to 'body' so is not 'contained' by a pane
        helper: function() {
        	//callFirst(); // can call function here to save button for example..
            z=jQuery(this).clone().appendTo('.ontop').css({
                'zIndex': 5, 'position':'absolute'
            }).attr("id","circle_"+count)//.attr("ondbclick","callme()");
            count++;
            
            console.debug("z is "+z)
            return z;
        },
        cursor: 'move',
        containment: ".ontop"
       
    });
	var toadd=""
	// makes ontop droppable
    jQuery('.ontop').droppable({
        //activeClass: 'ui-state-hover',
        accept: '.component',
        drop: function(event, ui) {
            if (!ui.draggable.hasClass("dropped")){
            	
            	
            	toadd=jQuery(ui.helper).clone().addClass("dropped").draggable({cursor: 'move', containment: ".ontop"});
        		 jQuery(this).append(toadd);
                
                // first drop, then create it in the database, and set all parameters.
                $.getJSON('<%= add_answer_course_lecture_path(@course, @lecture) %>',{"left":toadd.position().left, "top":toadd.position().top, "quiz": <%=@quiz.id %>, "flag":true}, function(resp){
                	
                	storedData[resp['current'].id]=[false,"",""]
                	console.debug("current id issss "+ resp['current'].id)
                	console.debug("to add isss "+toadd.attr("id"))
                	toadd.attr("id", ""+resp['current'].id) 
                	console.debug("to add isss "+toadd.attr("id"))
                	toadd.attr("onclick","load('"+toadd.attr('id')+"')")
	        		toadd.attr("rel","popover").attr("data-content","Correct:<input name='group1' id='correct_"+toadd.attr('id') +"' style='margin-left:20px;margin-bottom:2px' type='radio'/><br>Explanation:<input id='explain_"+toadd.attr('id') +"' type='text' /><br><input type='button'  class='btn btn-primary' value='Save' onclick=save('"+toadd.attr('id')+"') data-dismiss='clickover' /><input type='button' data-dismiss='clickover' class='btn' value='Cancel'/><input type='button' onclick=remove('"+toadd.attr('id')+"') class='btn btn-danger' value='Remove' data-dismiss='clickover'/>")//.attr()
	                toadd.attr("data-original-title","")
	                toadd.clickover({ global_close: false, template:  '<div class="popover myclass"><div class="arrow"></div><div class="popover-inner myclass"><div class="popover-content"><p></p></div></div></div>'})//.dblclick(function() {
               
                });
                }else{
                	// dragging inside the div
                
                toadd=jQuery(ui.helper)  // every time a button is dragged it is here in toadd. could get its position and save it.
                
                console.debug("new position is "+toadd.position().top+" and id is "+toadd.id+" explanation is ")//+document.getElementById('explain_'+toadd.id).value() )
               	saveAll(); // save all when change position.
                }
               
            }
        });
    });


$(document).ready(function() {
  //first of all, will get the data at the very beginning
  var old= <%= raw @old %>
  for(i=0; i<old.length; i++)
  {               
  	var toadd = $('<img />').attr({ 'id': old[i].id , 'src': '/assets/button8.png' });
  	toadd= toadd.addClass("component").addClass("dropped").draggable({cursor: 'move',containment: ".ontop"});
    storedData[old[i].id]=[old[i].correct,old[i].answer, old[i].explanation]
    toadd.css({"top":old[i].ycoor+"px", "left":old[i].xcoor+"px", 'zIndex': 5, 'position':'absolute'})
    toadd.attr("onclick","load('"+toadd.attr('id')+"')")
	toadd.attr("rel","popover").attr("data-content","Correct:<input group='group1' id='correct_"+toadd.attr('id') +"' style='margin-left:20px;margin-bottom:2px' type='radio'/><br>Answer: <textarea rows=3 id='answer_"+toadd.attr('id') +"' type='text' /><br>Explanation:<textarea rows=3 id='explain_"+toadd.attr('id') +"' type='text' /><br><input type='button'  class='btn btn-primary' value='Save' onclick=save('"+toadd.attr('id')+"') data-dismiss='clickover' /><input type='button' data-dismiss='clickover' class='btn' value='Cancel'/><input type='button' onclick=remove('"+toadd.attr('id')+"') class='btn btn-danger' value='Remove' data-dismiss='clickover'/>")//.attr()
	toadd.attr("data-original-title","")
	toadd.clickover({ global_close: false, template:  '<div class="popover myclass"><div class="arrow"></div><div class="popover-inner myclass"><div class="popover-content"><p></p></div></div></div>'})//.dblclick(function() {
     $('#ontop').append(toadd)           
  }
});


</script>
 



<!-- Should move this somewhere else later -->

<script>

var pop


document.addEventListener( "DOMContentLoaded", function() {
	
pop = Popcorn.youtube( "#youtube", "<%=  @lecture.url %>",{ width: 400, controls: 0}); //youtube unlike normal html5 needs to be run from a webserver
//var pop = Popcorn( Popcorn.youtube( '#youtube', 'http://www.youtube.com/watch?v=H9BXF6xJy54', { width: 400, controls: 0 } ) );

pop.controls( false ); 
 
pop.on("loadeddata", function(){
	this.currentTime(<%= @quiz.time %>)
	this.pause;
	 console.debug("pop duration isss"+this.currentTime())  
	});                        

                          

}, false );



$(document).ready(function() {
  $('.ontop').click(function(e) {
    var offset = $(this).offset();
  	left= parseFloat(e.pageX) - parseFloat(offset.left) //not clientX because client depends on window.. so numbers change when scrolling.
  	right = parseFloat(e.pageY) - parseFloat(offset.top)
  	
  	console.debug("offset is "+ left)
  	console.debug("left is "+left + " and top is "+right)
  	
    //document.getElementById('pos').innerHTML = 'Mouse position is: X='+left+' Y='+right;
	//document.getElementById('pos').style.left = left;
	//document.getElementById('pos').style.top = right;
	//document.getElementById('pos').style.display='block';
  });
  $('.ontop').dblclick(function(e) {
    var offset = $(this).offset();
  	left= parseInt(e.pageX) - parseInt(offset.left) -5//not clientX because client depends on window.. so numbers change when scrolling.
  	top2 = parseInt(e.pageY) - parseInt(offset.top) -5
  	
  	console.debug("offset is "+ left)
  	console.debug("offset is "+ top2)
  	
  	
  	// OK SO OVER HERE CREATE A NEW BUTTON AND ADD IT TO DROAPPABLE WITH ALL REQUIRED ATTRIBUTES LIKE WHEN DRAGGING. ALTER BELOW.
  	
  	
  	var toadd = $('<img />').attr({'src': '/assets/button8.png' });
  	toadd= toadd.addClass("component").addClass("dropped").draggable({cursor: 'move',containment: ".ontop"});
    
    toadd.css({"top":top2+"px", "left":left+"px", 'zIndex': 5, 'position':'absolute'})
    $('#ontop').append(toadd) 
     
  	 $.getJSON('<%= add_answer_course_lecture_path(@course, @lecture) %>',{"left":toadd.position().left, "top":toadd.position().top, "quiz": <%=@quiz.id %>, "flag":true}, function(resp){
                	
                	storedData[resp['current'].id]=[false,"", ""]
                	console.debug("current id issss "+ resp['current'].id)
                	console.debug("to add isss "+toadd.attr("id"))
                	toadd.attr("id", ""+resp['current'].id) 
                	console.debug("to add isss "+toadd.attr("id"))
                	toadd.attr("onclick","load('"+toadd.attr('id')+"')")
	        		toadd.attr("rel","popover").attr("data-content","Correct:<input name='group1' id='correct_"+toadd.attr('id') +"' style='margin-left:20px;margin-bottom:2px' type='radio'/><br>Answer: <textarea rows=3 id='answer_"+toadd.attr('id') +"' type='text' /><br>Explanation:<textarea rows=3 id='explain_"+toadd.attr('id') +"' type='text' /><br><input type='button'  class='btn btn-primary' value='Save' onclick=save('"+toadd.attr('id')+"') data-dismiss='clickover' /><input type='button' data-dismiss='clickover' class='btn' value='Cancel'/><input type='button' onclick=remove('"+toadd.attr('id')+"') class='btn btn-danger' value='Remove' data-dismiss='clickover'/>")//.attr()
	                toadd.attr("data-original-title","")
	                toadd.clickover({ global_close: false, template:  '<div class="popover myclass"><div class="arrow"></div><div class="popover-inner myclass"><div class="popover-content"><p></p></div></div></div>'})//.dblclick(function() {
               
    });
                
  	
     
  });
});


</script>
</head>

<div id="notify"></div>
<center><div class="ontop2" style="width:500px;border:8px solid;margin-top:0px;" >
<div class="ontop" id="ontop"></div>
<div id="youtube" style="width:500px;height:281px;"></div>
<div id="foo"></div>
</div></center>

<div style="width:100%;height:150px;">
<center style="margin-top: 10px"><!-- Drag the button: <%= image_tag "button6.png", :class=> "component"%> -->
<br><!-- <input class="btn" value="Save and Exit" onclick="saveAll()"/> -->
<!-- <%= button_to "Save", course_lecture_path(@course,@lecture), :class => "btn", :onclick => "saveAll()", :method => :get , :remote=> true%> -->	
</center>
</div>

app/views/groups/_review_questions.html.erb
<%= link_to @group.name , progress_teacher_course_path(@course, :g => @group, :type => "modules") %> >>  Review Questions
<br /><br />
<%= form_tag("save_review_questions") do %>
<%= submit_tag 'Save', :class => 'btn' , :style =>"float:right" %><br /><br />
<table class='table table-striped'>
<tr><td>Question</td><td>Lecture</td><td>Time</td><td>Hide?</td></tr>
<% @lecture_questions2.each do |question| %>
<tr>
<td><%= question.question %></td>
<td><%= Lecture.find(question.lecture_id).name %></td>	
<td><%= Time.seconds_to_time(question.time) %></td>
<td><%= check_box_tag "hide[#{question.id}]", 'yes', question.hide %></td>
</tr>
<% end %>
</table>
<%= submit_tag 'Save', :class => 'btn', :style =>"float:right" %>
<% end %>

app/views/groups/group_editor.html.erb
<%= render "shared/head" %>
<script src="http://popcornjs.org/code/dist/popcorn-complete.js"></script>
<% cache :hash => {:tag => @course.updated_at.to_i} do %>

<h4><%= link_to "#{@course.short_name} - #{@course.name}", course_editor_course_path(@course) %> : <%= @group.name %></h4>
<div class="row">
<div id="grouptable" class="span6">


<%= render "group" %>

<hr />
<!-- <%= link_to "New Module", new_course_group_path(@course), :style => "float:right"%> -->
</div>


<div class="span6" id="videospan" >
	<% if @quiz %>
		<center><%= render "coordinates"%></center>
	<% elsif @lecture %>  
		<center><%= render "lecture"%></center>
	 <% end %> 
</div>

</div>
<% end %>

app/views/groups/reload_editor.js.erb
//console.log("back")
$('#tree').html("<%= escape_javascript(raw render("courses/course"))%>");

app/views/groups/show.html.erb
<%= render 'shared/head' %>

<p>
  <b>Name:</b>
  <%= @group.name %>
</p>

<p>
  <b>Description:</b>
  <%= @group.description %>
</p>

<p>
  <b>Course:</b>
  <%= @group.course_id %>
</p>

<p>
  <b>Appearance Time:</b>
  <%= @group.appearance_time %>
</p>


<p>
  <b>Lectures:</b>
  <% @group.lectures.each do |l| %>
  	 <%=link_to l.name, course_lecture_path(@course,l) %>
  <% end %>
</p>

<p>
  <b>Quizzes:</b>
  <% @group.quizzes.each do |q| %>
  	 <%=link_to q.name, course_quiz_path(@course,q)%>
  <% end %>
</p>


<%= link_to 'Edit', edit_course_group_path(@course,@group) %> |
<%= link_to 'Back', course_groups_path(@course) %>

app/views/groups/update.js.erb
<!-- Reloading 3 partials, and opening tree at correct position. -->
$('#tree').html("<%= escape_javascript(raw render("courses/course"))%>");
$('#middle').html("<%= escape_javascript(raw render("statistics", :group2 => @group_new))%>");
$('#details').html("<%= escape_javascript(raw render("details", :group2 => @group_new))%>");