config/routes.rb
OnlineEdu::Application.routes.draw do
  #resources :groups

  resources :online_quiz_grades

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config
  get "home/index"
  #get "courses/new"

  #get "courses/index"

  #get "courses/create"

  #get "courses/update"

  resources :online_answers

  resources :online_quizzes

  resources :documents

  resources :quiz_grades

  resources :answers

  resources :questions
  
  resources :evaluations do
    collection do
      get 'get'
    end
  end

 # namespace :teacher do
 #   resources :courses
 # end  

  resources :courses do
  member do
    get 'remove_student'
    get 'add_student'
    get 'student_show'
    get 'courseware'
    get 'courseware_teacher'
    get 'enrolled_students'
    get 'progress_teacher'
    get 'progress_teacher_detailed'
    get 'progress'
    post 'student_quiz'
    get 'student_notifications'
    get 'course_editor'
    get 'student_grade'
    get 'dynamic_quizzes'
    get 'student_quiz_grade'
    get 'student_lecture_grade'
    get 'send_email'
    post 'send_email_through'
    get 'send_batch_email'
    post 'send_batch_email_through'
    
  end
    match '/events(/:year(/:month))' => 'events#index', :as => :event, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
    match "events/:id" => "events#show"
    resources :announcements do
      member do
        get 'reload'
      end
    end
    resources :groups do #at first had it over quizzes and lectures, but then a lecture/quiz might not be part of a module! so shouldn't need module to access lecture.. could create lectures and then put them part of a group.
      member do
        get 'new_or_edit'
        get 'group_editor'
        get 'statistics'
        get 'details'
        get 'display_quizzes'
        get 'display_questions'
        get 'new_document'
        get 'review_questions'
        post 'save_review_questions'
      end
      collection do
        post 'sort'
      end
    end
    resources :quizzes do
      member do
        get 'new_or_edit'
        get 'middle'
        get 'details'
        put 'update_questions'
      end
      collection do
        post 'sort'
      end
    end
    resources :lectures do
      member do
        get 'add_quiz'
        get 'remove_quiz'
        get 'coordinates'
        get 'add_answer'
        get 'remove_answer'
        get 'get_answers'
        #get 'save_answers'
        get 'save_answers2'
        get 'save_online'
        get 'answered'
        get 'insert_quiz'
        get 'confused'
        get 'confused_question'
        get 'seen'
        get 'new_or_edit'
        get 'new_quiz'
        get 'save_duration'
        get 'back'
        get 'pause'
        get 'getOldData'
        get 'middle'
        get 'details'
        get 'reload_invideo_quizzes'
      end
      collection do
        post 'sort'
      end
    end    
  end

  authenticated :user do
    #root :to => 'home#index'
    root :to => 'courses#index' #later make this home#index when we have a home#index!!
  end
  
  #authenticated :admin_user do
  #  root :to => 'admin#dashboard'
  #end
  
  root :to => "home#index"
  
  devise_for :users
  resources :users do
    member do
      get "enroll"
      post "enroll_to_course"
    end
  end
  
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  load_and_authorize_resource   #cancan to check if user is allowed to perform an action. checks from ability.rb
  before_filter :correct_user, :except => [:index, :new, :create]
  before_filter :set_zone , :except => [:index, :new, :create]
  
  cache_sweeper :course_sweeper
  caches_action :new, :layout => false  #removed edit.. because content for doesn't work with caching action.
  caches_action :index, :layout => false , :cache_path => proc { |c|
  { :tag => current_user.id, :update => Course.our(current_user.id).maximum(:updated_at).to_i, :num => Course.our(current_user.id).count } #so when change signed in user, then cache is stale.
  }
  # GET /courses
  # GET /courses.json
  def correct_user
    # Checking to see if the current user is taking the course OR teaching the course, otherwise he is not authorised.
    @c=Course.find(params[:id])
    if !@c.users.include?(current_user) and !(@c.user == current_user)
      redirect_to courses_path, :alert => "You are not authorized to see requested page"
    end
  end
  
  def set_zone
    #Setting the time zone to the zone of the course, to be used throughout.
    @course=Course.find(params[:id])
    Time.zone= @course.time_zone
  end
  
  def index
    # The course index page, with all the courses the teacher is giving OR the student is taking.
    # If this is an <tt> instructor </tt> I show the courses he's giving, else, the courses he's taking.
    if can? :create, Course    
        @courses = current_user.subjects 
        puts "can manage"
    else
        @courses = current_user.courses 
        puts "cant manage"
    end
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @courses }
    end
  end

  # GET /courses/1
  # GET /courses/1.json
  def student_show
    @course = Course.find(params[:id])
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @course }
    end
    
  end
  def show
    
    @course = Course.find(params[:id])
    @students= User.students
    
    # enrolled students
    @students2 = @course.enrolled_students  
    @student_ids= @students2.map{|a| a.id}
    
    #students not enrolled
    all_users2= @course.not_enrolled_students
    @student_ids2=all_users2.map{|a| a.id}
    
    #logger.debug("students areeeee #{@students}")

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @course }
    end
  end

  # GET /courses/new
  # GET /courses/new.json
  def new
    @course = Course.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @course }
    end
  end

  # GET /courses/1/edit
  def edit
    @course = Course.find(params[:id])
  end

  # POST /courses
  # POST /courses.json
  def create
    params[:course][:user_id]=current_user.id
    
    @course = Course.new(params[:course])

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render json: @course, status: :created, location: @course }
      else
        format.html { render action: "new" }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /courses/1
  # PUT /courses/1.json
  def update
    
    #don't need to add user_id here.. already exists.
    
    @course = Course.find(params[:id])
    
    # removing all groups that were removed already!
    logger.debug("course paramaeters areee #{params[:course]}")
    #params[:course][:groups_attributes].each do |k,v|
    #  if Group.where(:id => v["id"]).empty?
    #    params[:course][:groups_attributes].delete(k)
    #  end
    #end

    respond_to do |format|
      if @course.update_attributes(params[:course])
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course = Course.find(params[:id])
    @course.destroy

    respond_to do |format|
      format.html { redirect_to courses_url }
      format.json { head :no_content }
    end
  end
  
  ##### stopped here .. test ely ta7t and refactor.
  
  def remove_student
    @course = params[:id]
    @student=User.find(params[:student])
    @student.remove_student(@course)
    
    logger.debug @course
    text="Done"
    #render json: text
    redirect_to enrolled_students_course_path(Course.find(@course)), :notice => "#{@student.name} was removed from #{Course.find(@course).name}"
  end
  
  def add_student
    @course = Course.find(params[:id])
    @student=User.find(params[:student])
    @course.users<<@student
    if @course.save
    #@student.enrollments.where(:course_id => @course).destroy_all
    
      logger.debug @course
      text="successful"
    
      render json: text
    else
      render json: "failed"
    end
  end
  
  # NEED TO DIVIDE THIS!!
  
  def courseware
    if params[:q]   #requesting quiz
      #@q= Quiz.find(params[:q]) 
      @q= Quiz.where(:id => params[:q], :course_id => params[:id]).first
      if @q.nil? || @q.appearance_time > Time.zone.now.to_date || @q.group.nil?
        #params[:q]=nil
        redirect_to courseware_course_path(params[:id]), :alert => "No such quiz"
        puts "here redirecting to #{courseware_course_path(params[:id])}"
      else
      puts "q issssss #{@q.inspect}"
      @type="quiz"
      @highlight = "quiz_#{@q.id}"
      @typeGroup=@q.group.id
      @answers= QuizGrade.select("question_id, answer_id").where(:user_id=>current_user.id , :quiz_id=> params[:q])
      free_answers_list= FreeAnswer.select("question_id, answer").where(:user_id=>current_user.id , :quiz_id=> params[:q])
      @correct_answers= QuizGrade.where(:user_id=>current_user.id , :quiz_id=> params[:q]).select("distinct(question_id), grade")
      @out={}
      @correct={}
      
      @free_answers={}
      free_answers_list.each do |f|
        @free_answers[f.question_id]=f.answer
      end
      
      status = QuizStatus.where(:user_id => current_user.id, :quiz_id => @q.id, :course_id => params[:id])
      if (!status.empty? and status.first.status=="Submitted") #@q.due_date <= Time.zone.now or #won't disable if due date passed, but will know that submitted late.
        @disable=true
      end
      
      type=@q.quiz_type
      @alert_messages=[]
      day= 'day'.pluralize((Time.zone.now.to_date - @q.due_date).to_i)
      @alert_messages<< "Due date has passed -  #{@q.due_date.strftime("%d %b")} (#{(Time.zone.now.to_date - @q.due_date).to_i} #{day} ago)" if @q.due_date < Time.zone.now.to_date #if due date 5 april (night) then i have until 6 april..
      @alert_messages<<"You've already submitted the #{type.capitalize}" if !status.empty? and status.first.status=="Submitted" and flash[:from].nil?
      
      flash[:from]=nil #so it won't display anything.
      
      @answers.each do |a|
        if @out[a.question_id].nil?
            @out[a.question_id]=[a.answer_id]
        else
          @out[a.question_id]<<a.answer_id
        end   
      end
      
      #puts "correct_answers #{@correct_answers.length}"
      #puts "quiz count #{@q.questions}"
      
      #if @correct_answers.length == @q.questions.length   #Change this condition later, to display correct/incorrect IF and only IF quiz was submitted.
      if !status.empty? and status.first.status=="Submitted"
            @correct_answers.each do |s|
              @correct[s.question_id]= s.grade
              #puts "correct_answers #{s.question_id}"
            end
            
      end
      
      
      
      print "out isssss!!!!!!! #{@out}"
      end
    end
    
    if params[:l]   #requesting lecture
      #@q= Lecture.find(params[:l])
      @q= Lecture.where(:id => params[:l], :course_id => params[:id]).first
      if @q.nil? || @q.appearance_time > Time.zone.now.to_date || @q.group.nil?
        redirect_to courseware_course_path(params[:id]), :alert => "No such lecture"
      else
      @type="lecture" 
      @typeGroup=@q.group.id
      @highlight = "lecture_#{@q.id}"
      @url= get_answers_course_lecture_path(params[:id], params[:l])
      @saveOnline= save_online_course_lecture_path(params[:id], params[:l])
      @answered_path= answered_course_lecture_path(params[:id], params[:l])
      @confused_path=confused_course_lecture_path(params[:id], params[:l])
      @back_path=back_course_lecture_path(params[:id], params[:l])
      @pause_path=pause_course_lecture_path(params[:id], params[:l])
      @confused_question_path= confused_question_course_lecture_path(params[:id], params[:l])
      @seen_path=seen_course_lecture_path(params[:id], params[:l])
      @evaluation_path=evaluations_path()
      @get_evaluation_path=get_evaluations_path()
      
      #get next and previous lectures.
      next_lecture = @q.group.next_lecture(@q.position)
      if next_lecture.nil?
        @next_lecture=""
      else
        @next_lecture = courseware_course_path(@course, :l => next_lecture.id)
      end
      
      previous_lecture = @q.group.previous_lecture(@q.position)
      if previous_lecture.nil?
        @previous_lecture=""
      else
        @previous_lecture = courseware_course_path(@course, :l => previous_lecture.id)
      end
      
      ##################################     
      
      
      @first_evaluation= Evaluation.where(:course_id => params[:id], :lecture_id => params[:l], :user_id => current_user.id).empty?
      if !@first_evaluation
        @eval= Evaluation.where(:course_id => params[:id], :lecture_id => params[:l], :user_id => current_user.id).first
      end
      
      day= 'day'.pluralize((Time.zone.now.to_date - @q.due_date).to_i)
      @alert_messages=[]

app/controllers/teacher_controller.rb
class TeacherController < ActionController::Base
  load_and_authorize_resource
  protect_from_forgery

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path, :alert => exception.message
  end
  
  


end

app/helpers/courses_helper.rb
module CoursesHelper
  
def link_to_user(count)
#options[:class] = options.has_key?(:class) ? "#{options[:class]} user-link" : ""
  content_tag :div, :class => "accordian-body collapse", :id => "collapse#{count}" do
    "d"
  end
end 

# def notseen?(lect)
  # puts "over hereeeeeee #{LectureView.where(:lecture_id => lect, :course_id => params[:id], :user_id => current_user.id).inspect}"
  # puts "lecture id : #{lect}, course_id: #{params[:id]} user_id: #{current_user.id}"
  # return LectureView.where(:lecture_id => lect, :course_id => params[:id], :user_id => current_user.id).empty?
# end

def quiznotseen?(quiz)
  #return QuizGrade.where(:user_id => current_user.id, :quiz_id => quiz).empty? #later will check if status is submitted
  if Quiz.find(quiz).quiz_type == 'quiz'
    return QuizStatus.where(:user_id => current_user.id, :quiz_id => quiz, :course_id => params[:id], :status => "Submitted").empty?
  else
    return QuizStatus.where(:user_id => current_user.id, :quiz_id => quiz, :course_id => params[:id], :status => "Saved").empty?
  end
end


def notseen?(lect)
  lecture=Lecture.find(lect)
  return !lecture.done?(current_user.id)
end


end

app/helpers/teacher/courses_helper.rb
module Teacher::CoursesHelper
end

app/views/teacher/courses/_student.html.erb
<tr> 

<% if remove==false %>
<td>
<%= check_box_tag "studentsin[#{student.id}]", 1, false,:onClick => "add(#{student.id}, '#{add_student_course_path(@course)}')" %>
</td>
<% end%>

<td>
<%= student.name %>
</td>

<td>
<%= student.email %>
</td>

<td>
<% if remove %>
<%= link_to "Remove", course_path(@course), :onClick => "remove(#{student.id}, '#{remove_student_course_path(@course)}')", :remote => true , :id=> "students[#{student.id}]"%>
<% end%>
</td>


</tr>

app/views/teacher/courses/courseware.html.erb
<% content_for :extra do %>
    <ul class="nav nav-pills">
    <li class=<%= (current_page?(student_show_course_path(@course)) ? 'active' : nil)  %>>
    <%= link_to "Course Information", student_show_course_path(@course)%>
    </li>
    <li class=<%= (current_page?(courseware_course_path(@course)) ? 'active' : nil)  %>><%= link_to "Courseware", courseware_course_path(@course)%></li>
    <li class=<%= (current_page?(progress_course_path(@course)) ? 'active' : nil)  %>><%= link_to "Progress", progress_course_path(@course)%></li>
    </ul>
<% end %>


<div class="row">
<div class="span3">


<div class="accordion" id="accordion2">
<div class="accordion-group">
<div class="accordion-heading">
<a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseOne">
<center>Quizzes</center>
</a>
</div>
<% if @type == "quiz"%>
<div id="collapseOne" class="accordion-body collapse in">
<% else %>
<div id="collapseOne" class="accordion-body collapse">
<% end %>

<% @course.quizzes.each do |q| %>	
<div class="accordion-inner">
<%= link_to q.name, courseware_course_path(@course, :q => q) , :class => "quiz"%>
</div>
<% end %>


</div>
</div>
<div class="accordion-group">
<div class="accordion-heading">
<a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseTwo">
<center>Lectures</center>
</a>
</div>
<% if @type == "lecture"%>
<div id="collapseTwo" class="accordion-body collapse in">
<% else %>
<div id="collapseTwo" class="accordion-body collapse">
<% end %>
<% @course.lectures.each do |q| %>
<div class="accordion-inner">
<%= link_to q.name, courseware_course_path(@course, :l => q)  , :class => "lecture"%>
</div>
<% end %>
</div>
</div>
</div>

</div>

<div class="span9">
<% if @q %>
	<%= render @q %>
<% end %>
</div>
</div>

app/views/teacher/courses/courseware_teacher.html.erb
<% content_for :extra do %>
    <ul class="nav nav-pills">
    <li class=<%= (current_page?(course_path(@course)) ? 'active' : nil)  %>>
    <%= link_to "Course Information", course_path(@course)%>
    </li>
    <li class=<%= (current_page?(courseware_teacher_course_path(@course)) ? 'active' : nil)  %>><%= link_to "Courseware", courseware_teacher_course_path(@course)%></li>
    <li class=<%= (current_page?(enrolled_students_course_path(@course)) ? 'active' : nil)  %>><%= link_to "Enrolled Students", enrolled_students_course_path(@course)%></li>
    <li class=<%= (current_page?(progress_teacher_course_path(@course)) ? 'active' : nil)  %>><%= link_to "Progress", progress_teacher_course_path(@course)%></li>
    </ul>
<% end %>


<h4>Course Material:</h4>


<%= link_to "Lectures" , course_lectures_path(@course) %><br>
<%= link_to "Quizzes" , course_quizzes_path(@course) %> 

app/views/teacher/courses/create.html.erb
<h1>Teacher::Courses#create</h1>
<p>Find me in app/views/teacher/courses/create.html.erb</p>

app/views/teacher/courses/edit.html.erb
<h1>Editing course</h1>

<%= render 'form' %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

app/views/teacher/courses/enrolled_students.html.erb
<% content_for :extra do %>
    <ul class="nav nav-pills">
    <li class=<%= (current_page?(course_path(@course)) ? 'active' : nil)  %>>
    <%= link_to "Course Information", course_path(@course)%>
    </li>
    <li class=<%= (current_page?(courseware_teacher_course_path(@course)) ? 'active' : nil)  %>><%= link_to "Courseware", courseware_teacher_course_path(@course)%></li>
    <li class=<%= (current_page?(enrolled_students_course_path(@course)) ? 'active' : nil)  %>><%= link_to "Enrolled Students", enrolled_students_course_path(@course)%></li>
    <li class=<%= (current_page?(progress_teacher_course_path(@course)) ? 'active' : nil)  %>><%= link_to "Progress", progress_teacher_course_path(@course)%></li>
    </ul>
<% end %>

<div class="span6">

	  <!-- This is obtrusive javascript-->

<%= link_to "Students Enrolled", course_path(@course) , :onclick => "$('#invited_students').toggle()", :remote => true,  :id=>"show_now" %>
<div id="invited_students", width="100%", style="display: none; overflow: auto">
	<table width="100%"><%= render :partial => "student", :collection => @students , :locals=> {:remove=> true} %></table>
</div>
<br />
<%= link_to "Invite students?", course_path(@course) , :onclick => "$('#show_students').toggle()", :remote => true,  :id=>"show_now" %>
<div id="show_students", width="100%", style="display: none; overflow: auto">
	<table height="100px", width="100%"><%= render :partial => "student", :collection => @students , :locals=> {:remove=> false} %></table>

</div>
</div>



<script>
$(document).ready(function(){   // should put this somewhere elsee..
    
	
	//document.getElementById(b).parentNode.parentNode.style.display ="none";

var data =<%= @student_ids %>;
var data2=<%= @student_ids2 %>;
console.debug("i isssss "+data)

for(i=0; i<data.length; i++){
b= "studentsin_"+data[i]
document.getElementById(b).parentNode.parentNode.style.display ="none";
}

for(i=0; i<data2.length; i++){

b= "students["+data2[i]+"]"
console.debug(b)
document.getElementById(b).parentNode.parentNode.style.display ="none";
}

});
</script>

app/views/teacher/courses/new.html.erb
<h1>New course</h1>

<%= render 'form' %>

<%= link_to 'Back', courses_path %>

app/views/teacher/courses/progress.html.erb
<% content_for :extra do %>
    <ul class="nav nav-pills">
    <li class=<%= (current_page?(student_show_course_path(@course)) ? 'active' : nil)  %>>
    <%= link_to "Course Information", student_show_course_path(@course)%>
    </li>
    <li class=<%= (current_page?(courseware_course_path(@course)) ? 'active' : nil)  %>><%= link_to "Courseware", courseware_course_path(@course)%></li>
    <li class=<%= (current_page?(progress_course_path(@course)) ? 'active' : nil)  %>><%= link_to "Progress", progress_course_path(@course)%></li>
    </ul>
<% end %>


You have taken:
<table class="table table-striped">
<thead>
	<th>
		Quiz 
	</th>
	<th>
		Instructions
	</th>
	<th>
		Number of questions
	</th>
</thead>
<% @quizzes_taken.each do |q| %>
<tr>
	<td>
	<%= link_to q.name, courseware_course_path(@course, :q=>q.id) %>
	</td>
	<td>
	<%= q.instructions %>	
	</td>
	<td>
	<%= q.questions.size %>	
	</td>
</tr>
<% end %>
</table>

app/views/teacher/courses/progress_teacher.html.erb
<% content_for :extra do %>
    <ul class="nav nav-pills">
    <li class=<%= (current_page?(course_path(@course)) ? 'active' : nil)  %>>
    <%= link_to "Course Information", course_path(@course)%>
    </li>
    <li class=<%= (current_page?(courseware_teacher_course_path(@course)) ? 'active' : nil)  %>><%= link_to "Courseware", courseware_teacher_course_path(@course)%></li>
    <li class=<%= (current_page?(enrolled_students_course_path(@course)) ? 'active' : nil)  %>><%= link_to "Enrolled Students", enrolled_students_course_path(@course)%></li>
    <li class=<%= (current_page?(progress_teacher_course_path(@course)) ? 'active' : nil)  %>><%= link_to "Progress", progress_teacher_course_path(@course)%></li>
    </ul>
<% end %>


<table class="table table-striped">
<thead>
	<th>
		Student name 
	</th>
	<th>
		Student Email
	</th>
</thead>
<% @students.each do |q| %>
<tr>
	<td>
	<%= link_to q.name, progress_teacher_detailed_course_path(@course, :q=>q.id) , :class => "btn"%>
	</td>
	<td>
	<%= q.email %>	
	</td>
</tr>
<% end %>
</table>

app/views/teacher/courses/progress_teacher_detailed.html.erb
<% content_for :extra do %>
    <ul class="nav nav-pills">
    <li class=<%= (current_page?(course_path(@course)) ? 'active' : nil)  %>>
    <%= link_to "Course Information", course_path(@course)%>
    </li>
    <li class=<%= (current_page?(courseware_teacher_course_path(@course)) ? 'active' : nil)  %>><%= link_to "Courseware", courseware_teacher_course_path(@course)%></li>
    <li class=<%= (current_page?(enrolled_students_course_path(@course)) ? 'active' : nil)  %>><%= link_to "Enrolled Students", enrolled_students_course_path(@course)%></li>
    <li class=<%= (current_page?(progress_teacher_course_path(@course)) ? 'active' : nil)  %>><%= link_to "Progress", progress_teacher_course_path(@course)%></li>
    </ul>
<% end %>


<table class="table table-striped">
<thead>
	<th>
		Quiz 
	</th>
	<th>
		Instructions
	</th>
	<th>
		Number of questions
	</th>
</thead>
<% @quizzes_taken.each do |q| %>
<tr>
	<td>
	<%= q.name %>
	</td>
	<td>
	<%= q.instructions %>	
	</td>
	<td>
	<%= q.questions.size %>	
	</td>
</tr>
<% end %>
</table>

app/views/teacher/courses/show.html.erb
<% content_for :extra do %>
    <ul class="nav nav-pills">
    <li class=<%= (current_page?(course_path(@course)) ? 'active' : nil)  %>>
    <%= link_to "Course Information", course_path(@course)%>
    </li>
    <li class=<%= (current_page?(courseware_teacher_course_path(@course)) ? 'active' : nil)  %>><%= link_to "Courseware", courseware_teacher_course_path(@course)%></li>
    <li class=<%= (current_page?(enrolled_students_course_path(@course)) ? 'active' : nil)  %>><%= link_to "Enrolled Students", enrolled_students_course_path(@course)%></li>
    <li class=<%= (current_page?(progress_teacher_course_path(@course)) ? 'active' : nil)  %>><%= link_to "Progress", progress_teacher_course_path(@course)%></li>
    </ul>
<% end %>

<div class="row">
<div class="span6">
  <h3> <%= @course.short_name %> - <%= @course.name %></h3>


<p>
  <b>Start date:</b>
  <%= @course.start_date %>
</p>

<p>
  <b>Duration:</b>
  <%= @course.duration %>
</p>

<p>
  <b>Description:</b>
  <%= @course.description %>
</p>

<p>
  <b>Prerequisites:</b>
  <%= @course.prerequisites %>
</p>

<!-- <p>
  <b>User:</b>
  <%= @course.user_id %>
</p> -->
<br>

<%= link_to 'Edit', edit_course_path(@course) %> |
<%= link_to 'Back', courses_path %>
</div>

</div> 
<div class="row">
<div class="span6">
<!-- <h4>Course Material:</h4>

<%= link_to "Quizzes" , course_quizzes_path(@course) %> <!-- want to redirect to courses/1/quizzes  see how--> 
</div>

<div class="span6">
</div>
</div>


<!-- <script>
$(document).ready(function(){   // should put this somewhere elsee..
    
	
	//document.getElementById(b).parentNode.parentNode.style.display ="none";

var data =<%= @student_ids %>;
var data2=<%= @student_ids2 %>;
console.debug("i isssss "+data)

for(i=0; i<data.length; i++){
b= "studentsin_"+data[i]
document.getElementById(b).parentNode.parentNode.style.display ="none";
}

for(i=0; i<data2.length; i++){

b= "students["+data2[i]+"]"
console.debug(b)
document.getElementById(b).parentNode.parentNode.style.display ="none";
}

});
</script> -->

app/views/teacher/courses/student_quiz.html.erb
<% content_for :extra do %>
    <ul class="nav nav-pills">
    <li class=<%= (current_page?(student_show_course_path(@course)) ? 'active' : nil)  %>>
    <%= link_to "Course Information", student_show_course_path(@course)%>
    </li>
    <li class=<%= (current_page?(courseware_course_path(@course)) ? 'active' : nil)  %>><%= link_to "Courseware", courseware_course_path(@course)%></li>
    <li class=<%= (current_page?(progress_course_path(@course)) ? 'active' : nil)  %>><%= link_to "Progress", progress_course_path(@course)%></li>
    </ul>
<% end %>